name = "Dune"
uuid = "99f135e2-88c3-40ff-a1e2-47fd2cf0000f"
authors = ["Minsoo Kim"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
